
@url = http://localhost:8080/api/calendars
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYWxlbmRhciIsInN1YiI6InRlc3RAam9uZXMuY29tIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VzZXIiLCJleHAiOjE3MjcyNTU2OTV9.bBuqcNnpBC87CMwiUkrF-K74GnaJve9rOPlA06jubi4

GET {{url}}/user/4
Authorization: Bearer {{token}}


###

PUT {{url}}/3 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "calendarId": 3,
    "title": "My Calendar",
    "type": "PERSONAL",
    "userId": 3
}

###
POST {{url}}/create HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Workout Calendar",
    "type": "PERSONAL",
    "userId": 3
}

###

DELETE {{url}}/delete/1/1 HTTP/1.1
Authorization: Bearer {{token}}
