@url = http://localhost:8080/api/user



POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "test@jones.com",
    "password": "P@ssw0rd!"
}

###

POST {{url}}/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Mary",
    "lastName": "Lim",
    "email": "test@test.com",
    "username": "test@jones.com",
    "password": "P@ssw0rd!",
    "roles": []
}