@url = http://localhost:8080/api/CalendarRole
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYWxlbmRhciIsInN1YiI6ImpvZWVAam9uZXMuY29tIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VTRVIiLCJleHAiOjE3MjcyMTU4MDl9.Y5E3imucxIRfU_0cNnhX-hM2a0eyKkPlXIz2uvcrnYE

GET {{url}}/1 HTTP/1.1
Authorization: Bearer {{token}}