@url = http://localhost:8080/api/user
@token = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjYWxlbmRhciIsInN1YiI6InRlc3RAam9uZXMuY29tIiwiYXV0aG9yaXRpZXMiOiJST0xFX1VzZXIiLCJleHAiOjE3MjcyODA3NDV9.ny26a797g0ceNN2FDYAuk6Pu6aZ0-rfi3cMNdsU6K10


POST {{url}}/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "ADMIN",
    "password": "P@ssw0rd!"
}

###

POST {{url}}/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "Mary",
    "lastName": "Lim",
    "email": "test@test.com",
    "username": "test@jones.com",
    "password": "P@ssw0rd!",
    "roles": []
}

###

POST {{url}}/register HTTP/1.1
Content-Type: application/json

{
    "firstName": "coos",
    "lastName": "lim",
    "email": "test@test.com",
    "username": "test2@jones.com",
    "password": "P@ssw0rd!",
    "roles": []
}

###
DELETE {{url}}/delete/2 HTTP/1.1
Authorization: Bearer {{token}}